version: "3.9"

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    expose:
      - 6379   
  healthcheck:
    image: 'health-check:test'
    environment:
      - ENVIRONMENT=local
    ports:
      - 8080:8080
    expose:
      - 8080
